### ISSUE TITLE
Relax ex_doc dependency

### ISSUE THREAD

**Issue by fhunleth** [ityonemo/zigler#231]
Currently `zigler` has a strict dependency on `ex_doc 0.21.1`. See https://github.com/ityonemo/zigler/blob/master/mix.exs#L96. Later `ex_doc` versions fix a number of things including compiler warnings. Would it be possible to relax this dependency? I assume that there's some history here.

Thanks!

**Comment by ityonemo** [comment]
I think it should be, I pinned it because I am doing some sketchy things to correctly perform marshalling zig docstrings into elixir docs.  Unfortunately ex_doc API has not been solidified yet, and I haven't figured a good way to test to triple check that the docs are okay.  I'll relax the requirements, check to make sure docs are at least sane, and push 0.7.2.

**Comment by fhunleth** [comment]
Thanks! Also, no rush from me. I'm working with a local fork of `zigler` while I experiment with Nerves. 

Also, `zigler` is also holding back `nimble_parsec` from updating to 1.1.0. I think this is a safe update since upstream decided to go "1.0" and I don't believe that there were many changes from 0.5.0.
